
highlighter: pygments
github: [Repository metadata]

safe: true
lsi: false
#source: scienvitarso-blog
#destination: scienvitarso-blog/_site
#plugins:     scienvitarso-blog/_plugins
#layouts:     scienvitarso-blog/_layouts
#data_source: scienvitarso-blog/_data